var dataEmployee = [{ Name: 'Gecko', Email: 'Firefox 1.0', Phone: 'Win 98+ / OSX.2+' },
                 { Name: 'Peter', Email: 'abc@yahoo.com', Phone: '0291798' },
                 { Name: 'Mary', Email: 'Mary@yahoo..com', Phone: '98722554' },
                 { Name: 'John', Email: 'John@yaho.con', Phone: 'MS8778' },
                 { Name: 'Edision', Email: 'Edision@rewu.com', Phone: '17887121' },
                 { Name: 'Cary', Email: 'cary@sopm.cm', Phone: '145' },
                 { Name: 'Calop', Email: 'dasd@yahoo.cpm', Phone: '14578' },
                 { Name: 'Cure', Email: 'asd@uah.c0m', Phone: '789164' },
                 { Name: 'Cation', Email: 'philop@com', Phone: '1878' },
                 { Name: 'Phu', Email: 'phu@gmail.com', Phone: '9778112' },
                 { Name: 'Nam', Email: 'Smith@pms.com', Phone: '788912' },
                 { Name: 'Tai', Email: 'philop@com', Phone: '1878' },
                 { Name: 'Thanh', Email: 'phu@gmail.com', Phone: '9778112' },
                 { Name: 'Katina', Email: 'Katina@pms.com', Phone: '788778912' }
]
var dataUser = [{ LoginName: 'Gecko', FullName: 'Firefox 1.0', LastLogin: 'Win 98+ / OSX.2+', Status: 'Active' },
                {LoginName: 'Gecko', FullName: 'FirefoxFirefoxFirefoxFirefoxFirefoxFirefoxFirefoxFirefoxFirefox 1.0', LastLogin: 'Win 98+ / OSX.2+' ,Status:'Active'},
                 { LoginName: 'Peter', FullName: 'abc@yahoo.com', LastLogin: '0291798', Status: 'Confirm' },
                 { LoginName: 'Mary', FullName: 'Mary@yahoo..com', LastLogin: '98722554', Status: 'Pause' },
                 { LoginName: 'John', FullName: 'John@yaho.con', LastLogin: 'MS8778', Status: 'New' },
                 { LoginName: 'Edision', FullName: 'Edision@rewu.com', Phone: '17887121', Status: 'Active' },
                 { LoginName: 'Cary', FullName: 'cary@sopm.cm', LastLogin: '145', Status: 'Active' },
                 { LoginName: 'Calop', FullName: 'dasd@yahoo.cpm', LastLogin: '14578', Status: 'Active' },
                 { LoginName: 'Cure', FullName: 'asd@uah.c0m', LastLogin: '789164', Status: 'Active' },
                 { LoginName: 'Cation', FullName: 'philop@com', LastLogin: '1878', Status: 'Active' },
                 { LoginName: 'Phu', FullName: 'phu@gmail.com', LastLogin: '9778112', Status: 'Active' },
                 { LoginName: 'Nam', FullName: 'Smith@pms.com', LastLogin: '788912', Status: 'Active' },
                 { LoginName: 'Tai', FullName: 'philop@com', LastLogin: '1878', Status: 'Active' },
                 { LoginName: 'Thanh', FullName: 'phu@gmail.com', LastLogin: '9778112', Status: 'Active' },
                 { LoginName: 'Katina', FullName: 'Katina@pms.com', LastLogin: '788778912', Status: 'Active' }
]
//  headerCode: ['LoginName', 'FullName', 'LastLogin', , 'Status'],